variables:
  example: this is an example variable

stages:
  - version
  - version_update
  - stage1
  - stage2

version:
  stage: version
  script:
    - apt-get update
    - apt-get install git -y
    - BUILD_VERSION=$(git describe --tags) || true
    - echo BUILD_VERSION=${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}
    - |
      if [ "${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}" != "" ]
      then
        echo "true"
        git checkout main
        sed -i -e 's/SDK_VERSION=0.0.0/SDK_VERSION=\"test-sample-PHP-0710-${BUILD_VERSION}\"/g' settings.ini
        cat settings.ini
        git config --global user.email "vishalakshi.v1234@gmail.com"
        git config --global user.name "Vishalakshi Vishu"
        git status
        git add settings.ini
        git commit -m "updated sdk version"
        git push https://vishalakshi.v1234:glpat-KT5Mgyd-6e4aGyhCM6xL@gitlab.com/test-group838/test_sample_php_app.git HEAD:main
      fi

build:
  stage: stage1
  script:
    - echo "We are currently in stage 1"
    - echo "These are the contents of test.py"
    - echo $example

test:
  stage: stage2
  script:
    - echo "We are currently in stage 2"
    - echo "running python script"