variables:
  example: this is an example variable

stages:
  - version
  - version_update
  - stage1
  - stage2

version:
  stage: version
  script:
    - apt-get update
    - apt-get install git -y
    - BUILD_VERSION=$(git describe --tags) || true
    - echo BUILD_VERSION=${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}

version_update:
  stage: version_update
  script:
    - VERSION=${BUILD_VERSION%%-*}
    - echo ${VERSION}
    - |
      if [ "${VERSION}" != "" ]
      then
        sed -i -e 's/SDK_VERSION=0.0.0/SDK_VERSION=\"Sdk-Ris-PHP-0710-${VERSION}\"/g' settings.ini
      fi

build:
  stage: stage1
  script:
    - echo "We are currently in stage 1"
    - echo "These are the contents of test.py"
    - echo $example

test:
  stage: stage2
  script:
    - echo "We are currently in stage 2"
    - echo "running python script"