stages:
  - version
  - build
  - test

version:
  stage: version
  script:
    - apt-get update
    - apt-get install git -y
    - BUILD_VERSION=$(git describe --tags) || true
    - echo BUILD_VERSION=${BUILD_VERSION:-"0.0.0-${CI_COMMIT_SHORT_SHA}"}
    - BUILD_VERSION=`echo $BUILD_VERSION | cut -c-17`
    - SDK_VERSION="Sdk-Ris-PHP-"${BUILD_VERSION}
    - echo ${SDK_VERSION}

.php:
  image: roadiz/php73-runner
  before_script:
    # install dependencies
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - bash docker_install.sh
    - apt-get update
    - apt-get install zip unzip -y
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install
  script:
    - composer install

build:
  stage: build
  extends: .php
  
test:
  stage: test
  extends: .php
  script:
    - phpunit --version